---
- name: Create user valeria
  user:
    name: valeria.ivanovna
    password: "{{ 'tomasko1232002' | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
    createhome: yes
    update_password: always

- name: copy files to Trash
  copy:
    src: Trash
    dest: /home/valeria/.local/
