---
- name: Create user valeria
  user:
    name: valeria
    password: "{{ 'ivanovna' | password_hash('sha512') }}"
    shell: /bin/bash
    state: present
    createhome: yes
    update_password: always
