---
- name: copy python script
  copy:
    src: cve-2021-42013.py
    dest: /home/kali/Downloads/

- name: change /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "192.168.1.4  hladnespravy.sk"
    backup: yes
...