---
# Basic configuration of all defined devices

# Installation of common tools at all hosts
- name: Configuring hosts
  hosts: hosts
  become: true
  roles:
    - hosts

- name: Configuring valerias PC
  hosts: user
  become: true
  roles:
    - valeria

# Installation and configuration of each host
- name: Configuring devices separately
  hosts: hosts
  become: true
  tasks:
  - name: include role
    include_role:
      name: "{{ inventory_hostname }}"
...